### ISSUE TITLE
Problem with About the Author Link 

### ISSUE THREAD

**Issue by kalendar** [talbano/intro-measurement#1]
The "About the Author" link doesn't work. It looks like a lack of a trailing slash is causing the server to do some wacky port forwarding stuff.

index.Rmd, Line 20: <li><a href="https://cehs01.unl.edu/aalbano" target="_blank">About the author</a></li>

**Comment by talbano** [comment]
Thanks for pointing this out. Should be fixed now. Only took 2 years :)
